spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?characterEncoding=utf-8
    username: root
    password: Hwq2003Sjtu_SE##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: eBook-backend

server:
  port: 8080
